In [2]:
import pandas as pd

In [3]:
pop = pd.read_csv("fact_population_un.csv")
econ = pd.read_csv("fact_economics_imf.xls.csv")
water = pd.read_csv("fact_water_access.csv")
base = pd.read_csv("fact_country_year.csv")
country = pd.read_csv("dim_country_lookup.csv")

In [4]:
pop.head()
econ.head()
water.head()
base.head()

,COUNTRY,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
0,"Liechtenstein, Principality of",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.041,0.043,0.043,0.044,0.045,0.046,NaN,NaN,NaN,NaN
1,Canada,10.980,11.304,10.951,11.024,11.302,11.657,12.004,12.332,12.711,...,18.973,19.748,20.341,20.723,21.009,21.080,NaN,NaN,NaN,NaN
2,Honduras,2160.861,2133.804,2183.575,2222.247,2366.597,2464.850,2574.283,2724.965,2938.810,...,66813.898,74749.009,80686.569,86300.122,95066.366,100495.041,106338.384,112815.742,119722.508,126957.554
3,Honduras,3.673,3.790,3.908,4.029,4.154,4.283,4.411,4.544,4.680,...,10.117,10.294,10.475,10.659,10.846,11.037,11.231,11.428,11.629,11.833
4,"Bahamas, The",0.211,0.215,0.220,0.225,0.230,0.234,0.238,0.242,0.247,...,0.394,0.399,0.404,0.408,0.413,0.417,0.421,0.425,0.429,0.434

In [5]:
pop.columns

Index(['country', 'year', 'population', 'population_growth_rate'], dtype='str')

In [7]:
pop = pop.rename(columns={
    "Location": "country",
    "Time": "year",
    "TPopulation1Jan": "population",
    "PopGrowthRate": "population_growth_rate"
})

pop = pop[["country", "year", "population", "population_growth_rate"]]

In [8]:
pop["year"] = pd.to_numeric(pop["year"], errors="coerce")
pop["population"] = pd.to_numeric(pop["population"], errors="coerce")
pop["population_growth_rate"] = pd.to_numeric(pop["population_growth_rate"], errors="coerce")

In [9]:
pop = pop.dropna()
pop = pop.drop_duplicates(subset=["country", "year"])

In [10]:
water = water.rename(columns={
    "name": "country",
    "wat_basal_t": "basic_water_access_total"
})

water = water[["country", "year", "basic_water_access_total"]]

water["year"] = pd.to_numeric(water["year"], errors="coerce")
water["basic_water_access_total"] = pd.to_numeric(water["basic_water_access_total"], errors="coerce")

water = water.dropna()

In [11]:
base = base[["country", "year", "water_consumption_per_capita"]]

base["year"] = pd.to_numeric(base["year"], errors="coerce")
base["water_consumption_per_capita"] = pd.to_numeric(base["water_consumption_per_capita"], errors="coerce")

base = base.dropna()

KeyError: "None of [Index(['country', 'year', 'water_consumption_per_capita'], dtype='str')] are in the [columns]"

In [12]:
base.columns

Index(['COUNTRY', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', '2026', '2027', '2028', '2029', '2030'],
      dtype='str')

In [13]:
base = base.rename(columns={"COUNTRY": "country"})

In [14]:
base = base.melt(
    id_vars=["country"],
    var_name="year",
    value_name="water_consumption_per_capita"
)

In [15]:
base["year"] = pd.to_numeric(base["year"], errors="coerce")
base["water_consumption_per_capita"] = pd.to_numeric(base["water_consumption_per_capita"], errors="coerce")

In [16]:
base = base.dropna()
base = base.drop_duplicates(subset=["country", "year"])

In [17]:
base.head()

        country  year  water_consumption_per_capita
1        Canada  1980                        10.980
2      Honduras  1980                      2160.861
4  Bahamas, The  1980                         0.211
6   Puerto Rico  1980                         3.203
8         Qatar  1980                         0.245

In [18]:
valid_countries = set(country["country"].str.strip())

KeyError: 'country'

In [19]:
country.columns

Index(['geo', 'name', '1800', '1801', '1802', '1803', '1804', '1805', '1806',
       '1807',
       ...
       '2091', '2092', '2093', '2094', '2095', '2096', '2097', '2098', '2099',
       '2100'],
      dtype='str', length=303)